resources:
  - name: microservices
    type: git
    source:
       uri: https://github.com/sindrus/microservices
       branch: master

jobs:
  - name: frontend-test
    plan:
    - get: microservices
    - task: testing
      file: microservices/build.yml
