resources:
  - name: microservices
    type: git
    source:
       uri: git@github.com:sindrus/microservices.git
       branch: master

jobs:
  - name: frontend-test
    plan:
    - get: microservices
      trigger: true
    - task: testing
      file: microservices/concourse/frontend-test.yml
