resources:
  - name: microservices
    type: git
    source:
       uri: https://github.com/sindrus/microservices
       branch: master

jobs:
  - name: frontend-test
    plan:
    - get: microservices
      trigger: true
    - task: testing
      file: microservices/concourse/frontend-test.yml
